services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=books'
      - 'POSTGRES_PASSWORD=mysecretpassword'
      - 'POSTGRES_USER=asim'
    ports:
      - '5433:5432'
