services:
  business-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=business_db'
      - 'POSTGRES_PASSWORD=pg_business_password'
      - 'POSTGRES_USER=business_user'
    ports:
      - '5434:5432'
  business-redis:
    image: 'redis:latest'
    ports:
      - '6381:6379'