services:
  auth-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=auth_db'
      - 'POSTGRES_PASSWORD=pg_auth_password'
      - 'POSTGRES_USER=auth_user'
    ports:
      - '5433:5432'
  auth-redis:
    image: 'redis:latest'
    ports:
      - '6380:6379'